spring.application.name=wyseflow
server.port=8082
spring.thymeleaf.cache=false

# RabbitMQ settings
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
# Longer retry intervals for client apps
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=10000
spring.rabbitmq.listener.simple.retry.max-attempts=10
spring.rabbitmq.listener.simple.retry.multiplier=2.0
# Don't immediately reject messages if services are down
spring.rabbitmq.listener.simple.default-requeue-rejected=true
# Manual ack to ensure message persistence
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1
