spring.application.name=his
server.port=8084
# Queue settings
spring.rabbitmq.template.default-receive-queue=his.request.queue
spring.rabbitmq.template.exchange=his.exchange
spring.rabbitmq.template.routing-key=his.request

# RabbitMQ settings
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=1.2
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1
# Enable dead letter queue for failed messages
spring.rabbitmq.listener.simple.default-requeue-rejected=false
